
rmiserver:
	javac RMIServer.java RMIClient.java AdminConsole.java
	java RMIServer
	
admin:
	javac AdminConsole.java RMIClient.java RMIServer.java
	java AdminConsole

mcserver:
	javac MCServer.java RMIClient.java RMIServer.java AdminConsole.java
	java MCServer

clear:
	rm classes/*.class
	rm *.class