
rmiserver:
	javac RMIClient.java RMIServer.java AdminConsole.java
	java RMIServer
admin:
	javac RMIClient.java RMIServer.java AdminConsole.java
	java AdminConsole

clear:
	rm classes/*.class
	rm *.class